account/urls.py
from django.conf.urls import url
from django.urls import path, include
from .views import register, login, activate, account_activation_sent, logout, index

# SET THE NAMESPACE!
app_name = 'account'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    path('register/', register, name='register'),
    path('logout/', logout, name='logout'),
    path('login/', login, name='login'),
    path('index/', index, name='index'),
    url(r'^account_activation_sent/$', account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'),
]

grabitapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from pages.views import index
from django.conf.urls.static import static
from rest_framework.routers import DefaultRouter
router = DefaultRouter()
urlpatterns = [
    # path('', include(router.urls)),
    path('', index, name='index'),
    path('pages/', include('pages.urls')),
    path('account/', include('account.urls')),
    path('individual/', include('individual.urls')),
    path('hotspot/', include('hotspot.urls')),
    path('mush_store/', include('mush_store.urls')),
    path('search/', include('search.urls')),
    # path('api/', include('api.urls')),
    # url(r'api/', include('api.urls')),
    path('o/', include('oauth2_provider.urls')),
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('admin/', admin.site.urls),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.conf.urls import url
from django.urls import path, include
from .views import *
# SET THE NAMESPACE!
app_name = 'pages'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[

    path('index/', index, name='index'),
    # path('register/', register, name='register'),
    path('guide/', guide, name='guide'),
    path('listing/', listing, name='listing'),
    path('contact/', contact, name='contact'),
    path('listing/', listing, name='listing'),
    path('primary/', primary, name='primary'),
    path('secondary/', secondary, name='secondary'),
    path('faq/', faq, name='faq'),
   
]

search/urls.py
from django.urls import path, include # new

from .views import HomePageView, SearchResultsView,  search_detail
app_name = 'search'

urlpatterns = [
    path('search/', SearchResultsView.as_view(), name='search'),
    # path('<int:plant_id>/search_detail/', search_detail, name='search_detail'),
    path('<int:hotspot_id>/search_detail/', search_detail, name='search_detail'),
    path('', HomePageView.as_view(), name='home'),
]

search/models.py
# Create your models here.
from django.contrib.postgres.operations import TrigramExtension
from django.db import models,  migrations


class Migration(migrations.Migration):
  
    operations = [
        TrigramExtension(),
        
    ]

search/views.py
from django.shortcuts import render
from django.contrib.postgres.aggregates import StringAgg
from django.contrib.postgres.search import (
    SearchQuery, SearchRank, SearchVector, TrigramSimilarity,
)
from processor.models import (
Business, CapitalInvestmentRequirements, MarketAnalysis, Risk, CapitalInvestmentRequirementsItem, GeneralCosts, DirectCosts, DirectCostsItem, ProjectProductCostPriceStructure, ProductionOperatingCosts
)
from django.views.generic import TemplateView, ListView, DetailView
from django.db.models import Q, F
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.core.paginator import Paginator
from hotspot.models import  Hotspot, ActiveHotspot
import csv
from io import StringIO
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.files import File
from django.http import HttpResponse, StreamingHttpResponse
from django.utils.text import slugify



def search_detail(request,hotspot_id):
        totaldict = {}
        price_structure_total = float()
        desiel_pump_pricedict = {}
        petrol_pump_pricedict = {}
        addressdict = {}
        gas_pump_pricedict = {}
        price = float()
        hotspot = Hotspot.objects.get(id=hotspot_id)
        id = hotspot.id
        try:
                cpr = ActiveHotspot.objects.get(hotspot_id=id) 
                print('active hot spot found ',cpr.id, ' ___', cpr.desiel_pump_price)
                desiel_pump_pricedict[cpr.id] = []
                gas_pump_pricedict[cpr.id] = []
                petrol_pump_pricedict[cpr.id] = []
                desiel_pump_pricedict[cpr.id].append(cpr.desiel_pump_price)
                gas_pump_pricedict[cpr.id].append(cpr.gas_pump_price)
                petrol_pump_pricedict[cpr.id].append(cpr.petrol_pump_price)


        except (TypeError, ValueError, OverflowError, Hotspot.DoesNotExist):
                        error_message = 'Data  not added yet'

        
        context = {
                'name': hotspot.reference,
                'city': hotspot.city,
                'hotspot': hotspot,
                'desiel_pump_pricedict': desiel_pump_pricedict,
                'gas_pump_pricedict': gas_pump_pricedict,
                'petrol_pump_pricedict': petrol_pump_pricedict,
        }
        return render(request, 'pages/hotspot_detail.html', context )

class HomePageView(TemplateView):
    template_name = 'cities/home.html'


class Echo:
    """An object that implements just the write method of the file-like
    interface.
    """
    def write(self, value):
        """Write the value by returning it, instead of storing in a buffer."""
        return value

class SearchResultsView(ListView):
   
    template_name = 'pages/search_result.html'

    

    # queryset = City.objects.filter(name__icontains='Gweru')

    def get_queryset(self, **kwargs):
        
        text_query = self.request.GET.get('q')
        city_query = self.request.GET.get('q')
        province_query = self.request.GET.get('q')
        fuel_type_query = self.request.GET.get('q')
        production_type_query = self.request.GET.get('q')
        labour_query = self.request.GET.get('q')
        year_return_query = self.request.GET.get('q')


#To execute a more complex query we have to use three new Django objects: 
# SearchVector, SearchQuery, SearchRank  from postgres contrib
        search_query = SearchQuery(text_query) & SearchQuery(city_query) | SearchQuery(fuel_type_query)
        search_vector = SearchVector('reference', weight='A' ) + SearchVector('current_volume', weight='B')
        search_rank = SearchRank(search_vector, search_query)
        trigram_similarity = TrigramSimilarity('reference', text_query)

#Ranking Searches
        global object_list, paged_object_list
        object_list = Hotspot.objects.annotate(
             rank=search_rank 
            ).order_by(
            '-rank'
            )
        print('objet found',object_list)


        paginator = Paginator(object_list,3)
        page = self.request.GET.get('page')
        paged_object_list = paginator.get_page(page)


        return paged_object_list


    def get_context_data(self, **kwargs):
        
        context = super().get_context_data(**kwargs)
        total = dict()
        cap_item = []
        address = []
        desiel_pump_pricedict = {}
        petrol_pump_pricedict = {}
        addressdict = {}
        gas_pump_pricedict = {}
        business = paged_object_list
        print('hot spot',business)
        price = float()
        for a in business:
                try:
                        cpr = ActiveHotspot.objects.get(hotspot_id=a.id) 
                        print('active hot spot found ',cpr.id, ' ___', cpr.desiel_pump_price)
                        desiel_pump_pricedict[cpr.id] = []
                        gas_pump_pricedict[cpr.id] = []
                        petrol_pump_pricedict[cpr.id] = []
                        desiel_pump_pricedict[cpr.id].append(cpr.desiel_pump_price)
                        gas_pump_pricedict[cpr.id].append(cpr.gas_pump_price)
                        petrol_pump_pricedict[cpr.id].append(cpr.petrol_pump_price)
                except (TypeError, ValueError, OverflowError, ActiveHotspot.DoesNotExist):
                        dcost = 'Risk not added yet'       


        for b in business:
                addressdict[b.id] = []
                address = 'Zimbabwe' + ' ' + str(b.city) + ' ' +  str(b.neigbhourhood) + ' ' + str(b.residence)
                addressdict[b.id].append(address)
                print("ADRESS addressdict ", addressdict)
        context['addressdict'] = addressdict
        print('active hot spot found desiel_pump_pricedict ',desiel_pump_pricedict) 
        context['desiel_pump_pricedict'] = desiel_pump_pricedict
        context['gas_pump_pricedict'] = gas_pump_pricedict
        context['petrol_pump_pricedict'] = petrol_pump_pricedict


        return context



templates/pages/ayci_partials/_about.html
<!-- About Us -->
<div class="g-bg-cover g-bg-pos-top-center g-bg-img-hero g-pt-100 g-pb-70" style="background-image: url(assets/img/bg/map-sketch.jpg);">
    <div class="g-pos-rel g-z-index-1">
      <!-- Heading -->
      <div class="g-max-width-750 text-center mx-auto g-mb-100">
        <h2 class="mb-4">Our goal</h2>
        <p class="g-font-size-16 g-line-height-2">
           To bring an awereness of Afica's wealth and to empower our communities with confidence when choosing a business portifolio for this generation and the next.</p>
      </div>
      <!-- End Heading -->

      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-3 g-mb-30">
            <!-- Product - Services -->
            <div class="text-center">
              <span class="u-icon-v3 u-icon-size--xl g-color-white g-bg-primary rounded-circle mb-4">
                <i class="icon-real-estate-001 u-line-icon-pro"></i>
              </span>

              <h3 class="h5 text-uppercase">We Find the Best</h3>
              <p>options only according to your environment</p>
            </div>
            <!-- End Product - Services -->
          </div>

          <div class="col-md-3 g-mb-30">
            <!-- Product - Services -->
            <div class="text-center">
              <span class="u-icon-v3 u-icon-size--xl g-color-white g-bg-primary rounded-circle mb-4">
                <i class="icon-real-estate-013 u-line-icon-pro"></i>
              </span>

              <h3 class="h5 text-uppercase">We Check</h3>
              <p>all financial requirement for a sustainable value addition business</p>
            </div>
            <!-- End Product - Services -->
          </div>

          <div class="col-md-3 g-mb-30">
            <!-- Product - Services -->
            <div class="text-center">
              <span class="u-icon-v3 u-icon-size--xl g-color-white g-bg-primary rounded-circle mb-4">
                <i class="icon-christmas-037 u-line-icon-pro"></i>
              </span>

              <h3 class="h5 text-uppercase">Bonuses</h3>
              <p>We bring all factors of a value chain all  bundled together</p>
            </div>
            <!-- End Product - Services -->
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- End About Us -->

templates/pages/ayci_partials/_alerts.html
{% if messages %}
    {% for message in messages %}
        <div id="message" class="container">
            <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
                <strong>
                    {% if message.level == DEFAUT_MESSAGE_LEVELS.ERROR %}
                        Error
                    {% else %}
                        {{ message.tags|title }}
                    {% endif %}
                </strong>
                {{ message }}
            </div>
        </div>
    {% endfor %}
{% endif %}

templates/pages/ayci_partials/_footer_bar.html
<section>
<!-- Footer -->
<footer class="container g-pt-100 g-pb-70">
    <div class="row">
      <div class="col-md-3 text-center text-md-left g-mb-30">
        <!-- Logo -->
        <a class="d-block d-lg-flex align-items-center g-color-main text-uppercase g-text-underline--none--hover g-mb-30" href="{% url 'pages:index'%}?next={{request.path}}">
          <span class="g-color-text g-font-size-35 g-line-height-0_7 g-opacity-0_4 mr-4"><i class="icon-real-estate-066 u-line-icon-pro"></i></span>
          <span class="d-block g-font-weight-600 g-line-height-1_4">
            Value Addition Portal
            <span class="d-block g-color-text g-font-size-10 text-center">Enriching Africa</span>
          </span>
        </a>
        <!-- End Logo -->

      </div>

      <div class="col-md-6 text-center g-mb-30">
        <span class="d-block g-color-text g-font-size-13 mb-4">&#169; Malin Greats. All Rights Reserved. 2020</span>

        <!-- Footer - List -->
        <!-- <ul class="list-inline mb-5">
          <li class="list-inline-item mx-3"><a class="u-link-v5 g-color-main g-color-primary--hover g-font-weight-500" href="#">For Rent</a></li>
          <li class="list-inline-item mx-3"><a class="u-link-v5 g-color-main g-color-primary--hover g-font-weight-500" href="#">For Sale</a></li>
          <li class="list-inline-item mx-3"><a class="u-link-v5 g-color-main g-color-primary--hover g-font-weight-500" href="#">New Buildings</a></li>
          <li class="list-inline-item mx-3"><a class="u-link-v5 g-color-main g-color-primary--hover g-font-weight-500" href="#">Agents</a></li>
          <li class="list-inline-item mx-3"><a class="u-link-v5 g-color-main g-color-primary--hover g-font-weight-500" href="#">Help</a></li>
          <li class="list-inline-item mx-3"><a class="u-link-v5 g-color-main g-color-primary--hover g-font-weight-500" href="#">Contact Us</a></li>
        </ul> -->
        <!-- End Footer - List -->

        <!-- Go to Top -->
        <a class="js-go-to u-go-to-v3 g-width-40 g-height-40 g-color-primary" href="#"
           data-offset-top="400"
           data-compensation="#js-header"
           data-show-effect="zoomIn">
          <i class="g-brd-gray-light-v3 g-brd-primary--hover rounded-0 fa fa-long-arrow-up"></i>
        </a>
        <!-- End Go to Top -->
      </div>

      <div class="col-md-3 text-center g-mb-30">
        <h3 class="g-font-weight-600 g-font-size-13 text-uppercase">Follow us on:</h3>

        <!-- Social Icons -->
        <ul class="list-inline mb-0">
          <li class="list-inline-item g-mx-2">
            <a class="u-icon-v2 g-width-35 g-height-35 g-brd-gray-light-v3 g-brd-primary--hover g-color-gray-dark-v5 g-color-white--hover g-bg-transparent g-bg-primary-dark-v1--hover g-font-size-13" href="#">
              <i class="fa fa-facebook"></i>
            </a>
          </li>
          <li class="list-inline-item g-mx-2">
            <a class="u-icon-v2 g-width-35 g-height-35 g-brd-gray-light-v3 g-brd-primary--hover g-color-gray-dark-v5 g-color-white--hover g-bg-transparent g-bg-primary-dark-v1--hover g-font-size-13" href="#">
              <i class="fa fa-twitter"></i>
            </a>
          </li>
          <li class="list-inline-item g-mx-2">
            <a class="u-icon-v2 g-width-35 g-height-35 g-brd-gray-light-v3 g-brd-primary--hover g-color-gray-dark-v5 g-color-white--hover g-bg-transparent g-bg-primary-dark-v1--hover g-font-size-13" href="#">
              <i class="fa fa-tumblr"></i>
            </a>
          </li>
          <li class="list-inline-item g-mx-2">
            <a class="u-icon-v2 g-width-35 g-height-35 g-brd-gray-light-v3 g-brd-primary--hover g-color-gray-dark-v5 g-color-white--hover g-bg-transparent g-bg-primary-dark-v1--hover g-font-size-13" href="#">
              <i class="fa fa-pinterest-p"></i>
            </a>
          </li>
          <li class="list-inline-item g-mx-2">
            <a class="u-icon-v2 g-width-35 g-height-35 g-brd-gray-light-v3 g-brd-primary--hover g-color-gray-dark-v5 g-color-white--hover g-bg-transparent g-bg-primary-dark-v1--hover g-font-size-13" href="#">
              <i class="fa fa-google-plus"></i>
            </a>
          </li>
        </ul>
        <!-- End Social Icons -->
      </div>
    </div>
  </footer>
  <!-- End Footer -->

</section>


templates/pages/ayci_partials/_nav_bar.html
<section>
  <nav
    class="js-mega-menu navbar navbar-expand-lg g-brd-y g-brd-2 g-brd-primary-dark-v1 g-bg-primary g-pa-0"
  >
    <div class="container-fluid">
      <!-- Responsive Toggle Button -->
      <button
        class="navbar-toggler navbar-toggler-right btn g-line-height-1 g-brd-none g-pa-0"
        type="button"
        aria-label="Toggle navigation"
        aria-expanded="false"
        aria-controls="navBar"
        data-toggle="collapse"
        data-target="#navBar"
      >
        <span class="hamburger hamburger--slider g-px-0">
          <span class="hamburger-box">
            <span class="hamburger-inner"></span>
          </span>
        </span>
      </button>
      <!-- End Responsive Toggle Button -->

      <div class="col-auto order-lg-1">
        <!-- Search Form -->
        <form
          action="{% url 'search:search' %}"
          method="GET"
          id="searchform-1"
          class="g-min-width-180--sm g-min-width-315--xl g-brd-right g-brd-primary-dark-v1 g-pos-rel"
        >
          <span class="g-color-white g-pos-abs g-top-15"
            ><i class="fa fa-search"></i
          ></span>
          <input
            name="q"
            class="form-control w-100 g-brd-transparent g-color-white g-bg-transparent g-font-size-13 g-pl-25 g-py-18"
            type="text"
            placeholder="Search by location or fuel type"
          />
        </form>
        <!-- End Search Form -->
      </div>

      <!-- Navigation -->
      <div
        id="navBar"
        class="collapse navbar-collapse align-items-center order-lg-last g-brd-top g-brd-none--lg g-brd-primary-dark-v1"
      >
        <ul class="navbar-nav g-py-30 g-py-0--lg">
          <li class="nav-item">
            <a
              class="nav-link g-color-white g-brd-x--lg g-brd-primary-dark-v1 g-bg-primary-dark-v1--hover g-font-weight-600 g-font-size-default g-px-17 g-px-23--xl g-py-15"
              href="{% url 'pages:index'%}?next={{request.path}}"
            >
              Home
            </a>
          </li>

          <!-- Agents - Submenu -->
          <li class="nav-item hs-has-sub-menu">
            <a
              id="nav-link--page"
              class="nav-link g-color-white g-brd-right--lg g-brd-primary-dark-v1 g-bg-primary-dark-v1--hover g-font-weight-600 g-font-size-default g-px-17 g-px-23--xl g-py-15"
              href="#"
              aria-haspopup="true"
              aria-expanded="false"
              aria-controls="nav-submenu--page"
            >
              Hotspot Listing
            </a>

            <!-- Submenu -->
            <ul
              id="nav-submenu--page"
              class="hs-sub-menu list-unstyled u-shadow-v11 g-min-width-220 g-mt-2"
              aria-labelledby="nav-link--page"
            >
              <li class="dropdown-item">
                <a
                  class="nav-link g-color-text g-font-weight-600"
                  href="{% url 'pages:primary'%}?next={{request.path}"
                  >Commercial Fuel</a
                >
              </li>
              <li class="dropdown-item">
                <a
                  class="nav-link g-color-text g-font-weight-600"
                  href="{% url 'pages:secondary'%}?next={{request.path}"
                  >Non Commercial Fuel</a
                >
              </li>
            </ul>
            <!-- End Submenu -->
          </li>
          <!-- End Agents - Submenu -->

          <li class="nav-item">
            <a
              class="nav-link g-color-white g-brd-right--lg g-brd-primary-dark-v1 g-bg-primary-dark-v1--hover g-font-weight-600 g-font-size-default g-px-17 g-px-23--xl g-py-15"
              href="{% url 'pages:faq'%}?next={{request.path}"
            >
              Help
            </a>
          </li>
          <li class="nav-item">
            <a
              class="nav-link g-color-white g-brd-right--lg g-brd-primary-dark-v1 g-bg-primary-dark-v1--hover g-font-weight-600 g-font-size-default g-px-17 g-px-23--xl g-py-15"
              href="{% url 'pages:contact'%}?next={{request.path}}"
            >
              Contacts
            </a>
          </li>
        </ul>
      </div>
      <!-- End Navigation -->
    </div>
  </nav>
</section>

templates/pages/ayci_partials/_top_bar.html
{% load static %}
<section>
  <!-- Topbar -->
  <div class="g-bg-white">
    <div class="container-fluid g-py-15">
      <div class="row align-items-center">
        <div class="col-2 col-md-4 col-lg-2">
          <!-- Logo -->
          <a
            class="navbar-brand d-flex align-items-center g-color-main text-uppercase g-text-underline--none--hover"
            href="{% url 'pages:index'%}?next={{request.path}}"
          >
            <span
              class="g-color-text g-font-size-35 g-line-height-0_7 g-opacity-1 mr-4"
            >
              <img
                src="{% static 'assets/img/icons/ayci.png' %}"
                style="
                  height: 100px;
                  display: block;
                  position: absolute;
                  left: 52px;
                  height: 80px;
                  width: 80px;
                  top: 50%;
                  -webkit-transform: translateY(-50%);
                  -moz-transform: translateY(-50%);
                  -ms-transform: translateY(-50%);
                  -o-transform: translateY(-50%);
                  transform: translateY(-50%);
                "
              />
            </span>

            <span
              style="padding-left: 100px"
              class="d-block g-hidden-sm-down g-font-weight-600 g-line-height-1_4"
            >
              Africa Youths Council
              <span class="d-block g-color-text g-font-size-10 text-center"
                >African Youths</span
              >
            </span>
          </a>
          <!-- End Logo -->
        </div>

        <div class="col-10 col-md-8 col-lg-6 ml-auto">
          <!-- List -->
          <ul class="list-inline float-right mb-0">
            <!-- Guide -->
            <li class="list-inline-item g-pos-rel g-mx-2">
              <a
                id="guide-dropdown-invoker-2"
                class="u-link-v5 g-color-gray-dark-v5 g-color-primary--hover g-font-weight-500 g-font-size-12 g-pa-10"
                href="{% url 'pages:guide'%}?next={{request.path}}"
                aria-controls="guide-dropdown-2"
                aria-haspopup="true"
                aria-expanded="false"
                data-dropdown-event="hover"
                data-dropdown-target="#guide-dropdown-2"
                data-dropdown-type="css-animation"
                data-dropdown-duration="0"
                data-dropdown-hide-on-scroll="true"
                data-dropdown-animation-in="fadeIn"
                data-dropdown-animation-out="fadeOut"
              >
                Guide
              </a>
            </li>
            <!-- End Guide -->

            <li class="list-inline-item g-hidden-xs-down g-mx-2">
              <span class="g-color-gray-light-v1 g-pos-rel g-top-minus-1"
                >|</span
              >
            </li>
            <li class="list-inline-item g-hidden-xs-down g-mx-2">
              <a
                class="u-link-v5 g-color-gray-dark-v5 g-color-primary--hover g-font-weight-500 g-font-size-12 g-pa-10"
                href="{% url 'pages:contact'%}?next={{request.path}}"
              >
                <i
                  class="align-middle g-font-size-11 mr-1 icon-communication-033 u-line-icon-pro"
                ></i>
                Contacts
              </a>
            </li>
            <li class="list-inline-item g-hidden-xs-down g-mx-2">
              <span class="g-color-gray-light-v1 g-pos-rel g-top-minus-1"
                >|</span
              >
            </li>
            <li class="list-inline-item g-hidden-xs-down g-mx-2">
              <a
                class="u-link-v5 g-color-gray-dark-v5 g-color-primary--hover g-font-weight-500 g-font-size-12 g-pa-10"
                href="#"
              >
                <i
                  class="align-middle g-font-size-11 mr-1 icon-finance-206 u-line-icon-pro"
                ></i>
                Live Chat
              </a>
            </li>
            <li class="list-inline-item">
              <a
                class="u-link-v5 g-color-main g-color-white--hover g-bg-secondary g-bg-primary-dark-v1--hover g-font-weight-500 g-px-15 g-py-10"
                href="{% url 'pages:register'%}?next={{request.path}}"
                >Register</a
              >
            </li>
            <li class="list-inline-item">
              <a
                class="u-link-v5 g-color-white g-bg-primary g-bg-primary-dark-v1--hover g-font-weight-500 g-px-15 g-py-10"
                href="{% url 'pages:login'%}?next={{request.path}}"
                >Login</a
              >
            </li>
          </ul>
          <!-- End List -->
        </div>
      </div>
    </div>
  </div>
  <!-- End Topbar -->
</section>