account/urls.py
from django.conf.urls import url
from django.urls import path, include
from .views import register, login, activate, account_activation_sent, logout, index

# SET THE NAMESPACE!
app_name = 'account'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    path('register/', register, name='register'),
    path('logout/', logout, name='logout'),
    path('login/', login, name='login'),
    path('index/', index, name='index'),
    url(r'^account_activation_sent/$', account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'),
]

grabitapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from pages.views import index
from django.conf.urls.static import static
from rest_framework.routers import DefaultRouter
router = DefaultRouter()
urlpatterns = [
    # path('', include(router.urls)),
    path('', index, name='index'),
    path('pages/', include('pages.urls')),
    path('account/', include('account.urls')),
    path('individual/', include('individual.urls')),
    path('hotspot/', include('hotspot.urls')),
    path('mush_store/', include('mush_store.urls')),
    path('search/', include('search.urls')),
    # path('api/', include('api.urls')),
    # url(r'api/', include('api.urls')),
    path('o/', include('oauth2_provider.urls')),
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('admin/', admin.site.urls),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.conf.urls import url
from django.urls import path, include
from .views import *
# SET THE NAMESPACE!
app_name = 'pages'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[

    path('index/', index, name='index'),
    # path('register/', register, name='register'),
    path('guide/', guide, name='guide'),
    path('listing/', listing, name='listing'),
    path('contact/', contact, name='contact'),
    path('listing/', listing, name='listing'),
    path('primary/', primary, name='primary'),
    path('secondary/', secondary, name='secondary'),
    path('faq/', faq, name='faq'),
   
]

templates/pages/contact.html
{% extends 'pages/base.html' %}
{% load static %}
{% block content %}
<!-- Contacts -->
<div class="container g-py-100">
<header class="text-center g-mb-50">
<h1 class="h2">Contact Us</h1>
<p class="lead">Got a question? We'd love to hear from you!</p>
</header>

<div class="row text-center g-mb-50">
<div class="col-sm-6 col-md-4 g-mb-30">
 <!-- Icon Blocks -->
 <span class="g-font-size-40 g-color-primary mb-3">
   <i class="icon-real-estate-027 u-line-icon-pro"></i>
 </span>
 <h4 class="h5 g-font-weight-600 g-mb-5">Address</h4>
 <span class="d-block"> Mathe str., Gweru, 3DG</span>
 <!-- End Icon Blocks -->
</div>

<div class="col-sm-6 col-md-4 g-mb-30">
 <!-- Icon Blocks -->
 <span class="g-font-size-40 g-color-primary mb-3">
   <i class="icon-communication-062 u-line-icon-pro"></i>
 </span>
 <h4 class="h5 g-font-weight-600 g-mb-5">Phone Number</h4>
 <span class="d-block">+263 777 757 603</span>
 <!-- End Icon Blocks -->
</div>

<div class="col-sm-6 col-md-4 g-mb-30">
 <!-- Icon Blocks -->
 <span class="g-font-size-40 g-color-primary mb-3">
   <i class="icon-electronics-005 u-line-icon-pro"></i>
 </span>
 <h4 class="h5 g-font-weight-600 g-mb-5">Email</h4>
 <span class="d-block">info@valueadditionportal.co.zw</span>
 <!-- End Icon Blocks -->
</div>
</div>

<div class="text-center mx-auto g-width-70x--md">
<form>
 <div class="row">
   <div class="col-md-6 form-group g-mb-30">
     <input class="form-control g-color-gray-dark-v5 g-bg-white g-bg-white--focus g-brd-gray-light-v3 g-brd-primary--focus rounded-0 g-py-13 g-px-15" type="text" placeholder="Your name">
   </div>

   <div class="col-md-6 form-group g-mb-30">
     <input class="form-control g-color-gray-dark-v5 g-bg-white g-bg-white--focus g-brd-gray-light-v3 g-brd-primary--focus rounded-0 g-py-13 g-px-15" type="tel" placeholder="Your phone">
   </div>

   <div class="col-md-12 form-group g-mb-30">
     <input class="form-control g-color-gray-dark-v5 g-bg-white g-bg-white--focus g-brd-gray-light-v3 g-brd-primary--focus rounded-0 g-py-13 g-px-15" type="text" placeholder="Subject">
   </div>

   <div class="col-md-12 form-group g-mb-30">
     <textarea class="form-control g-color-gray-dark-v5 g-bg-white g-bg-white--focus g-brd-gray-light-v3 g-brd-primary--focus g-resize-none rounded-0 g-py-13 g-px-15" rows="7" placeholder="Message"></textarea>
   </div>
 </div>

 <div class="text-center">
   <button class="btn u-btn-primary text-uppercase rounded-0 g-px-25 g-py-13" type="submit" role="button">Send Message</button>
 </div>
</form>
</div>
</div>
<!-- End Contacts -->
{% endblock %}

templates/pages/faq.html
{% extends 'pages/base.html' %}
{% load static %}
{% block content %}

{% endblock %}

templates/pages/guide.html
{% extends 'pages/base.html' %}
{% load static %}
{% block content %}

{% endblock %}

templates/pages/login.html
{% extends 'pages/base.html' %} {% block content %}
<!-- Login - Heading -->
<div class="g-max-width-645 text-center g-pt-100 mx-auto g-mb-80">
  <h1 class="mb-0">Welcome back!</h1>
</div>
<!-- End Login - Heading -->

<!-- Login -->
<div class="container g-pb-30">
  <div class="row justify-content-center">
    <div class="col-md-6 col-lg-4 text-center g-mb-70">
      <h2 class="h5 mb-4">Sign in to your account</h2>
      {% include 'pages/partials/_alerts.html' %}
      <!-- Login Form -->
      <form class="g-mb-30" action="{% url 'account:login' %}" method="POST">
        {% csrf_token %}

        <div class="g-mb-20">
          <input
            class="form-control g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v3 g-brd-primary--hover rounded-0 g-py-13 g-px-15"
            name="username"
            type="text"
            placeholder="Email Address"
          />
        </div>

        <div class="g-mb-20">
          <input
            class="form-control g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v3 g-brd-primary--hover rounded-0 g-py-13 g-px-15"
            name="password"
            type="password"
            placeholder="Enter your Password"
          />
        </div>

        <button
          class="btn btn-block u-btn-primary g-color-white g-bg-primary-dark-v1--hover g-font-weight-600 g-font-size-12 text-uppercase rounded-0 g-px-25 g-py-15"
          type="submit"
          type="submit"
          value="Login"
        >
          Sign In
        </button>
      </form>
      <!-- End Login Form -->

      <div class="d-flex justify-content-between g-mb-10">
        <a
          class="d-block g-mb-10"
          href="{% url 'account:register'%}?next={{request.path}"
          >Create an account</a
        >
        <a class="d-block g-mb-10" href="page-forgot-password-1.html"
          >Forgot Password?</a
        >
      </div>
      <p class="g-font-size-12">
        Please view our
        <a class="g-color-text g-text-underline" href="#"
          >Personal Information Collection Statement</a
        >
      </p>
    </div>

    <div class="col-md-6 col-lg-5 ml-lg-5 g-mb-70">
      <!-- Icon Block -->
      <div class="media g-mb-30">
        <div class="d-flex mr-3">
          <span class="u-icon-v1 u-icon-size--lg g-color-text">
            <i class="icon-medical-022 u-line-icon-pro"></i>
          </span>
        </div>
        <div class="media-body">
          <h3 class="h5">Don’t miss a thing</h3>
          <p>
            Save your recomendations and stay updated on your favourite
            portfolios.
          </p>
        </div>
      </div>
      <!-- End Icon Block -->

      <!-- Icon Block -->
      <div class="media g-mb-30">
        <div class="d-flex mr-3">
          <span class="u-icon-v1 u-icon-size--lg g-color-text">
            <i class="icon-real-estate-083 u-line-icon-pro"></i>
          </span>
        </div>
        <div class="media-body">
          <h3 class="h5">Get organised</h3>
          <p>Receive recomendations for updated portfolios.</p>
        </div>
      </div>
      <!-- End Icon Block -->

      <!-- Icon Block -->
      <div class="media">
        <div class="d-flex mr-3">
          <span class="u-icon-v1 u-icon-size--lg g-color-text">
            <i class="icon-real-estate-014 u-line-icon-pro"></i>
          </span>
        </div>
        <div class="media-body">
          <h3 class="h5">Make the most of resources</h3>
          <p>
            Claim your portfolio and access insights and tools to help you
            understand the market.
          </p>
        </div>
      </div>
      <!-- End Icon Block -->
    </div>
  </div>
</div>
<!-- Login -->

{% endblock %}

templates/pages/loginn.html
{% extends 'pages/base.html' %}
{% load static %}
{% load easy_maps_tags %}
{% block content %}

   <!-- Login -->
    <section class="container g-py-100">
        <div class="row justify-content-center">
          <div class="col-sm-10 col-md-9 col-lg-6">
            <div class="g-brd-around g-brd-gray-light-v4 rounded g-py-40 g-px-30">
              <header class="text-center mb-4">
                <h2 class="h2 g-color-black g-font-weight-600">Signup</h2>
              </header>
  
              <!-- Form -->
              <form class="g-py-15">
                <div class="row">
                  <div class="col-xs-12 col-sm-6 mb-4">
                    <label class="g-color-gray-dark-v2 g-font-weight-600 g-font-size-13">First name:</label>
                    <input class="form-control g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v4 g-brd-primary--hover rounded g-py-15 g-px-15" type="email" placeholder="John">
                  </div>
  
                  <div class="col-xs-12 col-sm-6 mb-4">
                    <label class="g-color-gray-dark-v2 g-font-weight-600 g-font-size-13">Last name:</label>
                    <input class="form-control g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v4 g-brd-primary--hover rounded g-py-15 g-px-15" type="tel" placeholder="Doe">
                  </div>
                </div>
  
                <div class="mb-4">
                  <label class="g-color-gray-dark-v2 g-font-weight-600 g-font-size-13">Email:</label>
                  <input class="form-control g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v4 g-brd-primary--hover rounded g-py-15 g-px-15" type="email" placeholder="johndoe@gmail.com">
                </div>
  
                <div class="row">
                  <div class="col-xs-12 col-sm-6 mb-4">
                    <label class="g-color-gray-dark-v2 g-font-weight-600 g-font-size-13">Password:</label>
                    <input class="form-control g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v4 g-brd-primary--hover rounded g-py-15 g-px-15" type="password" placeholder="********">
                  </div>
  
                  <div class="col-xs-12 col-sm-6 mb-4">
                    <label class="g-color-gray-dark-v2 g-font-weight-600 g-font-size-13">Confirm Password:</label>
                    <input class="form-control g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v4 g-brd-primary--hover rounded g-py-15 g-px-15" type="password" placeholder="Password">
                  </div>
                </div>
  
                <div class="row justify-content-between mb-5">
                  <div class="col-8 align-self-center">
                    <label class="form-check-inline u-check g-color-gray-dark-v5 g-font-size-13 g-pl-25">
                      <input class="g-hidden-xs-up g-pos-abs g-top-0 g-left-0" type="checkbox">
                      <div class="u-check-icon-checkbox-v6 g-absolute-centered--y g-left-0">
                        <i class="fa" data-check-icon="&#xf00c"></i>
                      </div>
                      I accept the <a href="#">Terms and Conditions</a>
                    </label>
                  </div>
                  <div class="col-4 align-self-center text-right">
                    <button class="btn btn-md u-btn-primary rounded g-py-13 g-px-25" type="button">Signup</button>
                  </div>
                </div>
              </form>
              <!-- End Form -->
  
              <footer class="text-center">
                <p class="g-color-gray-dark-v5 g-font-size-13 mb-0">Already have an account? <a class="g-font-weight-600" href="page-login-1.html">signin</a>
                </p>
              </footer>
            </div>
          </div>
        </div>
      </section>
      <!-- End Login -->

      {% endblock %}

templates/pages/place_orders.html
hello

templates/pages/primary.html
{% extends 'pages/base.html' %}
{% load static %}
{% block content %}

{% endblock %}

templates/pages/register.html
{% extends 'pages/base.html' %} {% block content %}

<!-- Login - Heading -->
<div class="g-max-width-645 text-center g-pt-100 mx-auto g-mb-80">
  <h1 class="mb-4">Be part of Africa's finest fuel supply</h1>
  <p class="lead">
    Tailor your experience with Africa’s greatest fuel distributor. Access the
    most efficient supply close to you.
  </p>
</div>
<!-- End Login - Heading -->

<!-- Login -->
<div class="container g-pb-30">
  <div class="row justify-content-center">
    <div class="col-md-6 col-lg-4 text-center g-mb-70">
      <h2 class="h5 mb-4">Create your account today!</h2>

      <!-- Login Form -->
      {% include 'pages/partials/_alerts.html' %}
      <form class="g-mb-30" action="{% url 'account:register' %}" method="POST">
        {% csrf_token %}

        <div class="g-mb-20">
          <input
            name="email"
            class="form-control g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v3 g-brd-primary--hover rounded-0 g-py-13 g-px-15"
            type="email"
            placeholder="Email Address"
          />
        </div>
        <div class="g-mb-20">
          <input
            name="username"
            class="form-control g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v3 g-brd-primary--hover rounded-0 g-py-13 g-px-15"
            type="text"
            placeholder="User Name"
          />
        </div>
        <div class="g-mb-20">
          <input
            name="first_name"
            class="form-control g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v3 g-brd-primary--hover rounded-0 g-py-13 g-px-15"
            type="text"
            placeholder="First Name"
          />
        </div>
        <div class="g-mb-20">
          <input
            name="last_name"
            class="form-control g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v3 g-brd-primary--hover rounded-0 g-py-13 g-px-15"
            type="text"
            placeholder="Last Name"
          />
        </div>
        <div class="g-mb-20">
          <input
            name="password"
            class="form-control g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v3 g-brd-primary--hover rounded-0 g-py-13 g-px-15"
            type="password"
            placeholder="Create a Password"
          />
        </div>
        <div class="g-mb-20">
          <input
            name="password2"
            class="form-control g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v3 g-brd-primary--hover rounded-0 g-py-13 g-px-15"
            type="password"
            placeholder="Confirm Password"
          />
        </div>
        <div class="g-mb-20">
          <select
            name="role"
            class="js-custom-select w-100 h-100 u-select-v1 g-min-width-150 g-brd-left-none--md g-brd-gray-light-v3 g-color-main g-color-primary--hover g-pt-12 g-pb-13"
            required
            data-placeholder="Role"
            data-open-icon="fa fa-angle-down"
            data-close-icon="fa fa-angle-up"
          >
            <option>Account Type</option>
            <option
              class="g-brd-none g-color-main g-color-white--hover g-color-white--active g-bg-primary--hover g-bg-primary--active"
              value="individual"
            >
              Individual Car
            </option>

            <option
              class="g-brd-none g-color-main g-color-white--hover g-color-white--active g-bg-primary--hover g-bg-primary--active"
              value="farm"
            >
              Farm Vehicles
            </option>
            <option
              class="g-brd-none g-color-main g-color-white--hover g-color-white--active g-bg-primary--hover g-bg-primary--active"
              value="fleet"
            >
              Fleet Vehicles
            </option>
            <option
              class="g-brd-none g-color-main g-color-white--hover g-color-white--active g-bg-primary--hover g-bg-primary--active"
              value="mine"
            >
              Mine Vehicles
            </option>
            <option
              class="g-brd-none g-color-main g-color-white--hover g-color-white--active g-bg-primary--hover g-bg-primary--active"
              value="school"
            >
              School Vehicles
            </option>
          </select>
        </div>

        <button
          class="btn btn-block u-btn-primary g-color-white g-bg-primary-dark-v1--hover g-font-weight-600 g-font-size-12 text-uppercase rounded-0 g-px-25 g-py-15"
          type="submit"
        >
          Create Account
        </button>
      </form>
      <!-- End Login Form -->

      <a
        class="d-block g-mb-10"
        href="{% url 'account:login'%}?next={{request.path}}"
        >Already have an account? Sign in</a
      >
      <p class="g-font-size-12">
        Please view our
        <a class="g-color-text g-text-underline" href="#"
          >Personal Information Collection Statement</a
        >
      </p>
    </div>

    <div class="col-md-6 col-lg-5 ml-lg-5 g-mb-70">
      <!-- Icon Block -->
      <div class="media g-mb-30">
        <div class="d-flex mr-3">
          <span class="u-icon-v1 u-icon-size--lg g-color-text">
            <i class="icon-medical-022 u-line-icon-pro"></i>
          </span>
        </div>
        <div class="media-body">
          <h3 class="h5">Never queque for fuel</h3>
          <p>Stay updated on your account delivery, across any device.</p>
        </div>
      </div>
      <!-- End Icon Block -->

      <!-- Icon Block -->
      <div class="media g-mb-30">
        <div class="d-flex mr-3">
          <span class="u-icon-v1 u-icon-size--lg g-color-text">
            <i class="icon-real-estate-083 u-line-icon-pro"></i>
          </span>
        </div>
        <div class="media-body">
          <h3 class="h5">Get organised</h3>
          <p></p>
        </div>
      </div>
      <!-- End Icon Block -->

      <!-- Icon Block -->
      <div class="media">
        <div class="d-flex mr-3">
          <span class="u-icon-v1 u-icon-size--lg g-color-text">
            <i class="icon-real-estate-014 u-line-icon-pro"></i>
          </span>
        </div>
        <div class="media-body">
          <h3 class="h5">Make the most of your resources</h3>
          <p></p>
        </div>
      </div>
      <!-- End Icon Block -->
    </div>
  </div>
</div>
<!-- Login -->

{% endblock %}

templates/pages/search_detail_slider.html
<!-- Listing - Carousel Image -->
<div class="g-pos-rel">
    <label class="u-ribbon g-color-white g-bg-primary g-font-weight-600 g-pos-abs g-bottom-0 g-left-5 g-z-index-1 g-px-10 g-py-6">10 images</label>

    <div class="js-carousel g-pt-6 g-mx-2"
         data-infinite="true"
         data-slides-show="5"
         data-slides-scroll="1"
         data-rows="2"
         data-responsive='[{
           "breakpoint": 1200,
           "settings": {
             "slidesToShow": 5
           }
         }, {
           "breakpoint": 992,
           "settings": {
             "slidesToShow": 4
           }
         }, {
           "breakpoint": 768,
           "settings": {
             "slidesToShow": 3
           }
         }, {
           "breakpoint": 576,
           "settings": {
             "slidesToShow": 2
           }
         }, {
           "breakpoint": 446,
           "settings": {
             "slidesToShow": 2
           }
         }]'>
      <div class="js-slide g-px-3">
        <a class="js-fancybox d-block" href="javascript:;"
           data-fancybox="lightbox-gallery--01"
           data-src="assets/img-temp/1920x1080/img2.jpg"
           data-speed="350"
           data-caption="Lightbox Gallery">
          <img class="img-fluid" src="assets/img-temp/400x250/img13.jpg" alt="Image Description">
        </a>
      </div>

      <div class="js-slide g-px-3">
        <a class="js-fancybox d-block" href="javascript:;"
           data-fancybox="lightbox-gallery--01"
           data-src="assets/img-temp/1920x1080/img3.jpg"
           data-speed="350"
           data-caption="Lightbox Gallery">
          <img class="img-fluid" src="assets/img-temp/400x250/img14.jpg" alt="Image Description">
        </a>
      </div>

      <div class="js-slide g-px-3">
        <a class="js-fancybox d-block" href="javascript:;"
           data-fancybox="lightbox-gallery--01"
           data-src="assets/img-temp/1920x1080/img4.jpg"
           data-speed="350"
           data-caption="Lightbox Gallery">
          <img class="img-fluid" src="assets/img-temp/400x250/img15.jpg" alt="Image Description">
        </a>
      </div>

      <div class="js-slide g-px-3">
        <a class="js-fancybox d-block" href="javascript:;"
           data-fancybox="lightbox-gallery--01"
           data-src="assets/img-temp/1920x1080/img5.jpg"
           data-speed="350"
           data-caption="Lightbox Gallery">
          <img class="img-fluid" src="assets/img-temp/400x250/img16.jpg" alt="Image Description">
        </a>
      </div>

      <div class="js-slide g-px-3">
        <a class="js-fancybox d-block" href="javascript:;"
           data-fancybox="lightbox-gallery--01"
           data-src="assets/img-temp/1920x1080/img6.jpg"
           data-speed="350"
           data-caption="Lightbox Gallery">
          <img class="img-fluid" src="assets/img-temp/400x250/img17.jpg" alt="Image Description">
        </a>
      </div>

      <div class="js-slide g-px-3">
        <a class="js-fancybox d-block" href="javascript:;"
           data-fancybox="lightbox-gallery--01"
           data-src="assets/img-temp/1920x1080/img7.jpg"
           data-speed="350"
           data-caption="Lightbox Gallery">
          <img class="img-fluid" src="assets/img-temp/400x250/img18.jpg" alt="Image Description">
        </a>
      </div>

      <div class="js-slide g-px-3">
        <a class="js-fancybox d-block" href="javascript:;"
           data-fancybox="lightbox-gallery--01"
           data-src="assets/img-temp/1920x1080/img8.jpg"
           data-speed="350"
           data-caption="Lightbox Gallery">
          <img class="img-fluid" src="assets/img-temp/400x250/img19.jpg" alt="Image Description">
        </a>
      </div>

      <div class="js-slide g-px-3">
        <a class="js-fancybox d-block" href="javascript:;"
           data-fancybox="lightbox-gallery--01"
           data-src="assets/img-temp/1920x1080/img9.jpg"
           data-speed="350"
           data-caption="Lightbox Gallery">
          <img class="img-fluid" src="assets/img-temp/400x250/img20.jpg" alt="Image Description">
        </a>
      </div>

      <div class="js-slide g-px-3">
        <a class="js-fancybox d-block" href="javascript:;"
           data-fancybox="lightbox-gallery--01"
           data-src="assets/img-temp/1920x1080/img10.jpg"
           data-speed="350"
           data-caption="Lightbox Gallery">
          <img class="img-fluid" src="assets/img-temp/400x250/img21.jpg" alt="Image Description">
        </a>
      </div>

      <div class="js-slide g-px-3">
        <a class="js-fancybox d-block" href="javascript:;"
           data-fancybox="lightbox-gallery--01"
           data-src="assets/img-temp/1920x1080/img11.jpg"
           data-speed="350"
           data-caption="Lightbox Gallery">
          <img class="img-fluid" src="assets/img-temp/400x250/img22.jpg" alt="Image Description">
        </a>
      </div>
    </div>
  </div>
  <!-- End Listing - Carousel Image -->

templates/pages/signup.html
{% extends 'pages/base.html' %}
{% load static %}
{% load easy_maps_tags %}
{% block content %}

   <!-- Login -->
    <section class="container g-py-100">
        <div class="row justify-content-center">
          <div class="col-sm-10 col-md-9 col-lg-6">
            <div class="g-brd-around g-brd-gray-light-v4 rounded g-py-40 g-px-30">
              <header class="text-center mb-4">
                <h2 class="h2 g-color-black g-font-weight-600">Signup</h2>
              </header>
  
              <!-- Form -->
              <form class="g-py-15">
                <div class="row">
                  <div class="col-xs-12 col-sm-6 mb-4">
                    <label class="g-color-gray-dark-v2 g-font-weight-600 g-font-size-13">First name:</label>
                    <input class="form-control g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v4 g-brd-primary--hover rounded g-py-15 g-px-15" type="email" placeholder="John">
                  </div>
  
                  <div class="col-xs-12 col-sm-6 mb-4">
                    <label class="g-color-gray-dark-v2 g-font-weight-600 g-font-size-13">Last name:</label>
                    <input class="form-control g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v4 g-brd-primary--hover rounded g-py-15 g-px-15" type="tel" placeholder="Doe">
                  </div>
                </div>
  
                <div class="mb-4">
                  <label class="g-color-gray-dark-v2 g-font-weight-600 g-font-size-13">Email:</label>
                  <input class="form-control g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v4 g-brd-primary--hover rounded g-py-15 g-px-15" type="email" placeholder="johndoe@gmail.com">
                </div>
  
                <div class="row">
                  <div class="col-xs-12 col-sm-6 mb-4">
                    <label class="g-color-gray-dark-v2 g-font-weight-600 g-font-size-13">Password:</label>
                    <input class="form-control g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v4 g-brd-primary--hover rounded g-py-15 g-px-15" type="password" placeholder="********">
                  </div>
  
                  <div class="col-xs-12 col-sm-6 mb-4">
                    <label class="g-color-gray-dark-v2 g-font-weight-600 g-font-size-13">Confirm Password:</label>
                    <input class="form-control g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v4 g-brd-primary--hover rounded g-py-15 g-px-15" type="password" placeholder="Password">
                  </div>
                </div>
  
                <div class="row justify-content-between mb-5">
                  <div class="col-8 align-self-center">
                    <label class="form-check-inline u-check g-color-gray-dark-v5 g-font-size-13 g-pl-25">
                      <input class="g-hidden-xs-up g-pos-abs g-top-0 g-left-0" type="checkbox">
                      <div class="u-check-icon-checkbox-v6 g-absolute-centered--y g-left-0">
                        <i class="fa" data-check-icon="&#xf00c"></i>
                      </div>
                      I accept the <a href="#">Terms and Conditions</a>
                    </label>
                  </div>
                  <div class="col-4 align-self-center text-right">
                    <button class="btn btn-md u-btn-primary rounded g-py-13 g-px-25" type="button">Signup</button>
                  </div>
                </div>
              </form>
              <!-- End Form -->
  
              <footer class="text-center">
                <p class="g-color-gray-dark-v5 g-font-size-13 mb-0">Already have an account? <a class="g-font-weight-600" href="{% url 'account:login' %}">signin</a>
                </p>
              </footer>
            </div>
          </div>
        </div>
      </section>
      <!-- End Login -->

      {% endblock %}